version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - GIN_MODE=release
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
